### ISSUE TITLE
Could you add a license?

### ISSUE THREAD

**Issue by ysfchn** [melianmiko/ZeppOS-DevicesList#1]
I would like to use `zepp_devices.json` for my project, are there any conditions, limitations or something? And if you don't mind, can I ask the source of the list, do you find these online or is it written somewhere else? I know Zepp's own documentation keeps a list of some devices, but they don't list every device that runs Zepp OS.

Thanks!

**Comment by melianmiko** [comment]
Added MIT license.

> source of the list

Devices list file written by myself from tables on [this page](https://docs.zepp.com/docs/1.0/reference/related-resources/device-list/) and my own research results.
